services:

  kamailio-db:
    build:
      context: ./
      dockerfile: Dockerfile  # Dockerfile to fetch SQL scripts
      args:
        KAM_BRANCH: ${KAM_BRANCH:-upstream/5.8.6}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-kamailio}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KAMAILIO_SQL_SCRIPTS_TO_RUN=${KAMAILIO_SQL_SCRIPTS_TO_RUN}
      - CUSTOM_SQL_SCRIPTS_TO_RUN=${CUSTOM_SQL_SCRIPTS_TO_RUN}
    container_name: kamailio-db
    volumes:
      - ./psql_data/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./data:/var/lib/postgresql/data ## preserve data
      - ./kamailio_scripts:/all_postgres_db_scripts ## all fetched sql scripts that are available on the repo
    ports:
      - "5433:5432"
    networks:
      common-network:
        ipv4_address: 172.25.0.2  # Assign a specific IP

networks:
  common-network:
    external: true
