apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kamailio-db
spec:
  serviceName: kamailio-db
  replicas: 1
  selector:
    matchLabels:
      app: kamailio-db

  template:
    metadata:
      labels:
        app: kamailio-db

    spec:
      containers:
        - name: kamailio-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: {{ .Values.env_vars.postgres_user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env_vars.postgres_password | quote }}
            - name: KAMAILIO_SQL_SCRIPTS_TO_RUN
              value: {{ .Values.env_vars.kamailio_sql_scripts_to_run | quote }}
            - name: CUSTOM_SQL_SCRIPTS_TO_RUN
              value: {{ .Values.env_vars.custom_sql_scripts_to_run | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

            - name: pg_hba_config
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.env_vars.postgres_user }}"]
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.env_vars.postgres_user }}"]
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: pg_hba_config
          ConfigMap:
            name: kamailio-db-pg-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
